language: java
jdk:
  - oraclejdk8
sudo: false # faster builds

notifications:
  slack: adx-bob:BsJ9tURPxq0HcPLX9CY7AkfR
  webhooks:
    - https://webhooks.gitter.im/e/fbc3d5fbf22ba5342b5c

after_success:
  - bash <(curl -s https://codecov.io/bash)