/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ran_2' at '4/7/16 11:50 PM' with Gradle 2.12
 *
 * @author Ran_2, @date 4/7/16 11:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
